First unit branch
teenthofabud/sports-club pull request #2
Opened 2024-07-15 08:09 UTC by ginaserakalala

2024-07-22 21:01 UTC, ginaserakalala commented
Updated test cases to include private methods within Association and Player classes @anirbandas18

2024-07-26 13:18 UTC, anirbandas18 requested changes

2024-07-26 13:18 UTC, anirbandas18 commented on src/main/java/com.teenthofabud.sports.football/Association.java
> +    public static void resetCollection(){
reset is part of testing and not core business logic. core business logic should never allow for reset of entire data

2024-07-26 13:18 UTC, anirbandas18 commented on src/main/java/com.teenthofabud.sports.football/Player.java
> +    public static void resetPlayerCollection(){
reset is part of testing and not core business logic. core business logic should never allow for reset of entire data

2024-07-26 13:18 UTC, anirbandas18 commented on src/test/java/com/teenthofabud/sports/football/AssociationTest.java
> +    @AfterEach
self managed only in testing scope. should not affect the main service

2024-07-26 13:18 UTC, anirbandas18 commented on src/test/java/com/teenthofabud/sports/football/PlayerTest.java
> +        Player.resetPlayerCollection();
self managed only in testing scope. should not affect the main service

2024-07-26 13:18 UTC, anirbandas18 commented on src/test/java/com/teenthofabud/sports/football/PlayerTest.java
> +        Field collectionField = Player.class.getDeclaredField("COLLECTION");
Do not use reflection. Use the service methods to create your own logic for reset

2024-07-26 13:18 UTC, anirbandas18 commented on src/test/java/com/teenthofabud/sports/football/AssociationTest.java
> +        Field collectionField = Association.class.getDeclaredField("COLLECTION");
Do not use reflection. Use the service methods to create your own logic for reset

2024-08-03 12:41 UTC, anirbandas18 approved these changes

2024-08-03 12:41 UTC, merged